[features]
seeds = false
skip-lint = false
[programs.devnet]
coinflip = "t8sQWcvrATnFFMLo9Ex96G4e8bNAMW4hW79rx8bdPa7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/raider/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
